services:
  radar-train:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /home/pinkpanda/Downloads/RadarDataset:/app/data/radar_dataset
      - ./runs:/app/runs
    command: python train.py
